"""Copyright (c) 2024 Sara Mirzaee. All rights reserved.

disp-nisar: OPERA Displacement workflows for NISAR
"""

# flake8: noqa
# _version.py is autogenerated by setuptools_scm
from __future__ import annotations

from disp_nisar._version import version as __version__

# __all__ = ["__version__"]
