name: Docker

on:
  pull_request:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: Build & smoke test Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: docker build --network=host --tag=disp-nisar --file=docker/Dockerfile .
      - run: docker run --rm -t disp-nisar 
      # - run: docker run --rm test/disp-nisar gdalinfo NETCDF:/disp-nisar/tests/data/ALPSRP096740680-L1.0_GSLC.h5:/science/LSAR/GSLC/grids/frequencyA/HH
